//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminActivityLogDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminActivityLogDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gold.Resources.AdminActivityLogDescriptions", typeof(AdminActivityLogDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی {0} حذف شد.
        /// </summary>
        public static string AccessLevel_Delete {
            get {
                return ResourceManager.GetString("AccessLevel_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی {0} ویرایش شد.
        /// </summary>
        public static string AccessLevel_Edit {
            get {
                return ResourceManager.GetString("AccessLevel_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی {0} ثبت شد.
        /// </summary>
        public static string AccessLevel_Insert {
            get {
                return ResourceManager.GetString("AccessLevel_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاله {0} حذف شد.
        /// </summary>
        public static string Article_Delete {
            get {
                return ResourceManager.GetString("Article_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاله {0} ویرایش شد.
        /// </summary>
        public static string Article_Edit {
            get {
                return ResourceManager.GetString("Article_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاله {0} ثبت شد.
        /// </summary>
        public static string Article_Insert {
            get {
                return ResourceManager.GetString("Article_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت مقاله {0} تغییر کرد.
        /// </summary>
        public static string Article_StatusChanged {
            get {
                return ResourceManager.GetString("Article_StatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام ارسال شده در تاریخ {0} مربوط به {1} حذف شد..
        /// </summary>
        public static string ContactUsMessage_Delete {
            get {
                return ResourceManager.GetString("ContactUsMessage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} حذف شد.
        /// </summary>
        public static string Customer_Delete {
            get {
                return ResourceManager.GetString("Customer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت {0} مربوط به {1} حذف شد.
        /// </summary>
        public static string Customer_Delete_CardNumber {
            get {
                return ResourceManager.GetString("Customer_Delete_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ضروری {0} مربوط به {1} حذف شد.
        /// </summary>
        public static string Customer_Delete_EssentialNumber {
            get {
                return ResourceManager.GetString("Customer_Delete_EssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر {0} مربوط به {1} حذف شد.
        /// </summary>
        public static string Customer_Delete_ProfileImage {
            get {
                return ResourceManager.GetString("Customer_Delete_ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} ویرایش شد.
        /// </summary>
        public static string Customer_Edit {
            get {
                return ResourceManager.GetString("Customer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت {0} مربوط به {1} ویرایش شد.
        /// </summary>
        public static string Customer_Edit_CardNumber {
            get {
                return ResourceManager.GetString("Customer_Edit_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ضروری {0} مربوط به {1} ویرایش شد.
        /// </summary>
        public static string Customer_Edit_EssentialNumber {
            get {
                return ResourceManager.GetString("Customer_Edit_EssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور {0} ریست شد.
        /// </summary>
        public static string Customer_Edit_ResetPassword {
            get {
                return ResourceManager.GetString("Customer_Edit_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} ثبت شد.
        /// </summary>
        public static string Customer_Insert {
            get {
                return ResourceManager.GetString("Customer_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت {0} برای {1} ثبت شد.
        /// </summary>
        public static string Customer_Insert_CardNumber {
            get {
                return ResourceManager.GetString("Customer_Insert_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ضروری {0} برای {1} ثبت شد.
        /// </summary>
        public static string Customer_Insert_EssentialNumber {
            get {
                return ResourceManager.GetString("Customer_Insert_EssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی {0} مربوط به {1} حذف شد.
        /// </summary>
        public static string Document_Delete_BankCardNumber {
            get {
                return ResourceManager.GetString("Document_Delete_BankCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ضروری {0} مربوط به {1} حذف شد.
        /// </summary>
        public static string Document_Delete_EssentialNumber {
            get {
                return ResourceManager.GetString("Document_Delete_EssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی {0} مربوط به {1} ویرایش شد.
        /// </summary>
        public static string Document_Edit_BankCardNumber {
            get {
                return ResourceManager.GetString("Document_Edit_BankCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} ویرایش شد.
        /// </summary>
        public static string Document_Edit_CustomerInfo {
            get {
                return ResourceManager.GetString("Document_Edit_CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ضروری {0} مربوط به {1} ویرایش شد.
        /// </summary>
        public static string Document_Edit_EssentialNumber {
            get {
                return ResourceManager.GetString("Document_Edit_EssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند {0} برای {1} ثبت شد.
        /// </summary>
        public static string Document_Insert {
            get {
                return ResourceManager.GetString("Document_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی {0} برای {1} ثبت شد.
        /// </summary>
        public static string Document_Insert_BankCardNumber {
            get {
                return ResourceManager.GetString("Document_Insert_BankCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} ثبت شد.
        /// </summary>
        public static string Document_Insert_Customer {
            get {
                return ResourceManager.GetString("Document_Insert_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ضروری {0} برای {1} ثبت شد.
        /// </summary>
        public static string Document_Insert_EssentialNumber {
            get {
                return ResourceManager.GetString("Document_Insert_EssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند {0} مربوط به {1} حذف شد.
        /// </summary>
        public static string DocumentList_Delete {
            get {
                return ResourceManager.GetString("DocumentList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سند {0} مربوط به {1}، ضمانت {2} حذف شد.
        /// </summary>
        public static string DocumentList_Delete_Collateral {
            get {
                return ResourceManager.GetString("DocumentList_Delete_Collateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت {0} تومان قسط {1} سند {2} مربوط به {3} حذف شد.
        /// </summary>
        public static string DocumentList_Delete_PaymentOfInstallment {
            get {
                return ResourceManager.GetString("DocumentList_Delete_PaymentOfInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند {0} مربوط به {1} به  شماره سند {2} ویرایش شد.
        /// </summary>
        public static string DocumentList_Edit {
            get {
                return ResourceManager.GetString("DocumentList_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سند {0} مربوط به {1} از تسویه به فعال تغییر یافت.
        /// </summary>
        public static string DocumentList_Edit_ChangeToActive {
            get {
                return ResourceManager.GetString("DocumentList_Edit_ChangeToActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در سند {0} مربوط به {1}، ضمانت {2} ویرایش شد.
        /// </summary>
        public static string DocumentList_Edit_Collateral {
            get {
                return ResourceManager.GetString("DocumentList_Edit_Collateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند {0} مربوط به {1} تسویه شد.
        /// </summary>
        public static string DocumentList_Edit_DocumentCleared {
            get {
                return ResourceManager.GetString("DocumentList_Edit_DocumentCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سند {0} مربوط به {1} ویرایش شد.
        /// </summary>
        public static string DocumentList_Edit_DocumentDescription {
            get {
                return ResourceManager.GetString("DocumentList_Edit_DocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت {0} تومان قسط {1} سند {2} مربوط به {3} ویرایش شد و قسط به پرداخت شده تغییر یافت.
        /// </summary>
        public static string DocumentList_Edit_InstallmentChangedToPaid {
            get {
                return ResourceManager.GetString("DocumentList_Edit_InstallmentChangedToPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت قسط {0} سند {1} مربوط به {2} از پرداخت شده به پرداخت نشده تغییر یافت.
        /// </summary>
        public static string DocumentList_Edit_InstallmentChangedToUnpaid {
            get {
                return ResourceManager.GetString("DocumentList_Edit_InstallmentChangedToUnpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت {0} تومان قسط {1} سند {2} مربوط به {3} ویرایش شد.
        /// </summary>
        public static string DocumentList_Edit_PaymentOfInstallment {
            get {
                return ResourceManager.GetString("DocumentList_Edit_PaymentOfInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای سند {0} مربوط به {1}، ضمانت {2} ثبت شد.
        /// </summary>
        public static string DocumentList_Insert_Collateral {
            get {
                return ResourceManager.GetString("DocumentList_Insert_Collateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای قسط {0} سند {1} مربوط به {2}، پرداخت به مبلغ  {3} تومان ثبت شد و قسط به پرداخت شده تغییر یافت.
        /// </summary>
        public static string DocumentList_Insert_InstallmentChangedToPaid {
            get {
                return ResourceManager.GetString("DocumentList_Insert_InstallmentChangedToPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای قسط {0} سند {1} مربوط به {2}، پرداخت به مبلغ  {3} تومان ثبت شد.
        /// </summary>
        public static string DocumentList_Insert_PaymentOfInstallment {
            get {
                return ResourceManager.GetString("DocumentList_Insert_PaymentOfInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال  {0} حذف شد.
        /// </summary>
        public static string FAQ_Delete {
            get {
                return ResourceManager.GetString("FAQ_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال  {0} ویرایش شد.
        /// </summary>
        public static string FAQ_Edit {
            get {
                return ResourceManager.GetString("FAQ_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال  {0} ثبت شد.
        /// </summary>
        public static string FAQ_Insert {
            get {
                return ResourceManager.GetString("FAQ_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی  {0} حذف شد.
        /// </summary>
        public static string FAQCategory_Delete {
            get {
                return ResourceManager.GetString("FAQCategory_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی  {0} ویرایش شد.
        /// </summary>
        public static string FAQCategory_Edit {
            get {
                return ResourceManager.GetString("FAQCategory_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی  {0} ثبت شد.
        /// </summary>
        public static string FAQCategory_Insert {
            get {
                return ResourceManager.GetString("FAQCategory_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری {0} حذف شد.
        /// </summary>
        public static string Gallery_Delete {
            get {
                return ResourceManager.GetString("Gallery_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده {0} مربوط به گالری {1} حذف شد.
        /// </summary>
        public static string Gallery_Delete_Seller {
            get {
                return ResourceManager.GetString("Gallery_Delete_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری {0} ویرایش شد.
        /// </summary>
        public static string Gallery_Edit {
            get {
                return ResourceManager.GetString("Gallery_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده {0} مربوط به گالری {1} ویرایش شد.
        /// </summary>
        public static string Gallery_Edit_Seller {
            get {
                return ResourceManager.GetString("Gallery_Edit_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری {0} ثبت شد.
        /// </summary>
        public static string Gallery_Insert {
            get {
                return ResourceManager.GetString("Gallery_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده {0} برای گالری {1} ثبت شد.
        /// </summary>
        public static string Gallery_Insert_Seller {
            get {
                return ResourceManager.GetString("Gallery_Insert_Seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر {0} حذف شد.
        /// </summary>
        public static string Manager_Delete {
            get {
                return ResourceManager.GetString("Manager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر {0} ویرایش شد.
        /// </summary>
        public static string Manager_Edit {
            get {
                return ResourceManager.GetString("Manager_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر {0} ثبت شد.
        /// </summary>
        public static string Manager_Insert {
            get {
                return ResourceManager.GetString("Manager_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت {0} مربوط به سند {1}  حذف شد.
        /// </summary>
        public static string PaymentPendingConfirmation_Delete {
            get {
                return ResourceManager.GetString("PaymentPendingConfirmation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت {0} برای قسط {1} سند {2}  با مبلغ {3} تومان تایید شد.
        /// </summary>
        public static string PaymentPendingConfirmation_Insert {
            get {
                return ResourceManager.GetString("PaymentPendingConfirmation_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت {0} برای قسط {1} سند {2} با مبلغ  {3} تومان تایید شد و قسط به پرداخت شده تغییر یافت.
        /// </summary>
        public static string PaymentPendingConfirmation_Insert_InstallmentPaymented {
            get {
                return ResourceManager.GetString("PaymentPendingConfirmation_Insert_InstallmentPaymented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت {0} برای سند {1} به علت {2} تایید نشد.
        /// </summary>
        public static string PaymentPendingRejection_Insert {
            get {
                return ResourceManager.GetString("PaymentPendingRejection_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول  {0} گالری {1} حذف شد.
        /// </summary>
        public static string Product_Delete {
            get {
                return ResourceManager.GetString("Product_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول {0} گالری {1} ویرایش شد.
        /// </summary>
        public static string Product_Edit {
            get {
                return ResourceManager.GetString("Product_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول  {0} برای گالری {1} ثبت شد.
        /// </summary>
        public static string Product_Insert {
            get {
                return ResourceManager.GetString("Product_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی  {0} حذف شد.
        /// </summary>
        public static string ProductCategory_Delete {
            get {
                return ResourceManager.GetString("ProductCategory_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی  {0} ویرایش شد.
        /// </summary>
        public static string ProductCategory_Edit {
            get {
                return ResourceManager.GetString("ProductCategory_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی  {0} ثبت شد.
        /// </summary>
        public static string ProductCategory_Insert {
            get {
                return ResourceManager.GetString("ProductCategory_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر/ویدیو محصول  {0}  حذف شد.
        /// </summary>
        public static string ProductGallery_Delete {
            get {
                return ResourceManager.GetString("ProductGallery_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر/ویدیو برای محصول  {0}  ثبت شد.
        /// </summary>
        public static string ProductGallery_Insert {
            get {
                return ResourceManager.GetString("ProductGallery_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست  {0}  حذف شد.
        /// </summary>
        public static string RequestsToEditInformation_Delete {
            get {
                return ResourceManager.GetString("RequestsToEditInformation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست {0} آرشیو شد.
        /// </summary>
        public static string RequestsToEditInformation_Edit_Archived {
            get {
                return ResourceManager.GetString("RequestsToEditInformation_Edit_Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات نرخ طلا با قیمت {0} تومان برای طلای 18 عیار حذف شد.
        /// </summary>
        public static string Setting_Delete_GoldPrice {
            get {
                return ResourceManager.GetString("Setting_Delete_GoldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه های اجتماعی {0} حذف شد.
        /// </summary>
        public static string Setting_Delete_SocialNetworks {
            get {
                return ResourceManager.GetString("Setting_Delete_SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیشفرض پیام ها ویرایش شد.
        /// </summary>
        public static string Setting_Edit_DefaultTextMessages {
            get {
                return ResourceManager.GetString("Setting_Edit_DefaultTextMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات وام ویرایش شد.
        /// </summary>
        public static string Setting_Edit_LoanSettings {
            get {
                return ResourceManager.GetString("Setting_Edit_LoanSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکریپت ها ویرایش شد.
        /// </summary>
        public static string Setting_Edit_Scripts {
            get {
                return ResourceManager.GetString("Setting_Edit_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای صفحه {0} ویرایش شد.
        /// </summary>
        public static string Setting_Edit_SiteContent {
            get {
                return ResourceManager.GetString("Setting_Edit_SiteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه های اجتماعی {0} ویرایش شد.
        /// </summary>
        public static string Setting_Edit_SocialNetworks {
            get {
                return ResourceManager.GetString("Setting_Edit_SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات نرخ طلا با قیمت {0} تومان برای طلای 18 عیار ثبت شد.
        /// </summary>
        public static string Setting_Insert_GoldPrice {
            get {
                return ResourceManager.GetString("Setting_Insert_GoldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه های اجتماعی {0} ثبت شد.
        /// </summary>
        public static string Setting_Insert_SocialNetworks {
            get {
                return ResourceManager.GetString("Setting_Insert_SocialNetworks", resourceCulture);
            }
        }
    }
}
