//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DBOperationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBOperationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gold.Resources.DBOperationMessages", typeof(DBOperationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام تغییرات داده ها، برگشت داده شدند..
        /// </summary>
        public static string AllDataChangesAreRollBacked {
            get {
                return ResourceManager.GetString("AllDataChangesAreRollBacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ذخیره شد.
        /// </summary>
        public static string AllDataChangesAreSaved {
            get {
                return ResourceManager.GetString("AllDataChangesAreSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در هنگام عملیات رخ داده است.
        /// </summary>
        public static string AnErrorOccurredInOperation {
            get {
                return ResourceManager.GetString("AnErrorOccurredInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی هنگام افزودن داده رخ داده است.
        /// </summary>
        public static string AnErrorOccurredWhileAddingData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileAddingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی هنگام ویرایش داده رخ داده است.
        /// </summary>
        public static string AnErrorOccurredWhileEditingData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileEditingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی هنگام حذف داده رخ داده است.
        /// </summary>
        public static string AnErrorOccurredWhileRemovingData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileRemovingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی هنگام واکشی داده رخ داده است.
        /// </summary>
        public static string AnErrorOccurredWhileRetrievingData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileRetrievingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در هنگام برگشت در تغییرات داده ها.
        /// </summary>
        public static string AnErrorOccurredWhileRollBackingData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileRollBackingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در هنگام ذخیره داده ها، رخ داده است..
        /// </summary>
        public static string AnErrorOccurredWhileSavingData {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ها به درستی اضافه شدند.
        /// </summary>
        public static string DataAddedCorrectly {
            get {
                return ResourceManager.GetString("DataAddedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ها به درستی حذف شدند.
        /// </summary>
        public static string DataDeletedCorrectly {
            get {
                return ResourceManager.GetString("DataDeletedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ها به درستی ویرایش شدند.
        /// </summary>
        public static string DataEditedCorrectly {
            get {
                return ResourceManager.GetString("DataEditedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده به درستی یافت شد.
        /// </summary>
        public static string DataFoundedCorrectly {
            get {
                return ResourceManager.GetString("DataFoundedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده مورد نظر یافت نشد.
        /// </summary>
        public static string DataWasNotFound {
            get {
                return ResourceManager.GetString("DataWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده تکراری است.
        /// </summary>
        public static string ExistenceOfDuplicateData {
            get {
                return ResourceManager.GetString("ExistenceOfDuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل استفاده در جای دیگر مجاز به حذف اطلاعات نمی باشید.
        /// </summary>
        public static string NotAllowedToDeleteDueToUseElsewhere {
            get {
                return ResourceManager.GetString("NotAllowedToDeleteDueToUseElsewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده تکراری نیست.
        /// </summary>
        public static string NotExistenceOfDuplicateData {
            get {
                return ResourceManager.GetString("NotExistenceOfDuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست داده ها به درستی واکشی شدند.
        /// </summary>
        public static string TheDataListWasFetchedCorrectly {
            get {
                return ResourceManager.GetString("TheDataListWasFetchedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده ها به درستی واکشی شدند.
        /// </summary>
        public static string TheDataWasFetchedCorrectly {
            get {
                return ResourceManager.GetString("TheDataWasFetchedCorrectly", resourceCulture);
            }
        }
    }
}
