//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gold.Resources.UserMessages", typeof(UserMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام اقساط وام بطور کامل پرداخت شده است.
        /// </summary>
        public static string AllInstallmentsOfLoanHavebeenPaidInFull {
            get {
                return ResourceManager.GetString("AllInstallmentsOfLoanHavebeenPaidInFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجاز برای ثبت کالا میباشد.
        /// </summary>
        public static string AllowedForProductRegistration {
            get {
                return ResourceManager.GetString("AllowedForProductRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف مجاز برای ثبت کالا  در یک ساعت  برای شما پر شده است.
        /// </summary>
        public static string AllowedLimitForProductRegistrationHasBeenFilled {
            get {
                return ResourceManager.GetString("AllowedLimitForProductRegistrationHasBeenFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر دیگری با این اطلاعات در سایت ثبت نام کرده است.
        /// </summary>
        public static string AnotherUserHasRegisteredOnTheSiteWithThisInformation {
            get {
                return ResourceManager.GetString("AnotherUserHasRegisteredOnTheSiteWithThisInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای انجام این کار اطمینان دارید؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد انتخاب شده آرشیو شود؟.
        /// </summary>
        public static string AreYouSureForArchive {
            get {
                return ResourceManager.GetString("AreYouSureForArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف مطمئن هستید؟.
        /// </summary>
        public static string AreYouSureForDelete {
            get {
                return ResourceManager.GetString("AreYouSureForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با ویرایش سند، تمام اقساط این سند، به حالت پرداخت نشده در می آیند. آیا برای ویرایش اطلاعات، اطمینان دارید؟.
        /// </summary>
        public static string AreYouSureForEditDocument {
            get {
                return ResourceManager.GetString("AreYouSureForEditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه وارد شده برای مشتری دیگری ثبت شده است، آیا مایل به ثبت اطلاعات می باشید؟.
        /// </summary>
        public static string AreYouSureForRegisterIfMobileDuplicated {
            get {
                return ResourceManager.GetString("AreYouSureForRegisterIfMobileDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از ثبت رسید پرداخت، اطمینان دارید؟.
        /// </summary>
        public static string AreYouSureForRegisterRecipt {
            get {
                return ResourceManager.GetString("AreYouSureForRegisterRecipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با انجام این عملیات رمز عبور کاربر به شماره تلفن همراه اش تغییر می یابد. آیا از انجام این کار مطمئن هستید؟.
        /// </summary>
        public static string AreYouSureForResetPassword {
            get {
                return ResourceManager.GetString("AreYouSureForResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از ارسال پیام مطمئن هستید؟.
        /// </summary>
        public static string AreYouSureForSendMessage {
            get {
                return ResourceManager.GetString("AreYouSureForSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا این سند تسویه شود؟.
        /// </summary>
        public static string AreYouSureSettleDocument {
            get {
                return ResourceManager.GetString("AreYouSureSettleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل باید یک ضمانت برای این سند ثبت شود.
        /// </summary>
        public static string AtLeastOneCollateralIsRequiredForTheDocument {
            get {
                return ResourceManager.GetString("AtLeastOneCollateralIsRequiredForTheDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک شماره ضروری برای مشتری، الزامی است.
        /// </summary>
        public static string AtLeastOneEssentialNumberIsRequiredForTheCustomer {
            get {
                return ResourceManager.GetString("AtLeastOneEssentialNumberIsRequiredForTheCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت تسویه با مدیریت تماس بگیرید.
        /// </summary>
        public static string CallByAdminForSettleDocument {
            get {
                return ResourceManager.GetString("CallByAdminForSettleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجاز به تایید رسید پرداخت نمی باشید.
        /// </summary>
        public static string CanNotAllowToConfirmThisPaymentRecipt {
            get {
                return ResourceManager.GetString("CanNotAllowToConfirmThisPaymentRecipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام عملیات لغو پرداخت امکان پذیر نیست.
        /// </summary>
        public static string CanNottUnPayableTheInstallment {
            get {
                return ResourceManager.GetString("CanNottUnPayableTheInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر وضعیت محصول وجود ندارد.
        /// </summary>
        public static string CantChangeProductStatus {
            get {
                return ResourceManager.GetString("CantChangeProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف محصول وجود ندارد.
        /// </summary>
        public static string CantDeleteProduct {
            get {
                return ResourceManager.GetString("CantDeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ویرایش محصول وجود ندارد.
        /// </summary>
        public static string CantEditeProduct {
            get {
                return ResourceManager.GetString("CantEditeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام عملیات لغو پرداخت امکان پذیر است.
        /// </summary>
        public static string CanUnPayableTheInstallment {
            get {
                return ResourceManager.GetString("CanUnPayableTheInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که اطلاعات با اطلاعات شناسنامه ای شما مغایرت دارد،  اینجا کلیک کنید..
        /// </summary>
        public static string ClickForSendEditInformationReqest {
            get {
                return ResourceManager.GetString("ClickForSendEditInformationReqest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتخاب شده برای سند، بزرگتر از امروز است. آیا تایید میکنید؟.
        /// </summary>
        public static string ConfirmDocDateMessageForCreate {
            get {
                return ResourceManager.GetString("ConfirmDocDateMessageForCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مشتری با نام {0} حذف شد.
        /// </summary>
        public static string CustomerInfoByName0IsDeleted {
            get {
                return ResourceManager.GetString("CustomerInfoByName0IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای پرداخت باید تصویر یا تاریخ و ساعت و مبلغ واریز را وارد کنید.
        /// </summary>
        public static string CustomerPaymentValidationMessage {
            get {
                return ResourceManager.GetString("CustomerPaymentValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت حذف شد.
        /// </summary>
        public static string DataDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DataDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت حذف شد اما فایل حذف نشد.
        /// </summary>
        public static string DataDeletedSuccessfullyButFileNotDeleted {
            get {
                return ResourceManager.GetString("DataDeletedSuccessfullyButFileNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ویرایش  شد.
        /// </summary>
        public static string DataEditedSuccessfully {
            get {
                return ResourceManager.GetString("DataEditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت شد.
        /// </summary>
        public static string DataSavedSuccessfully {
            get {
                return ResourceManager.GetString("DataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سند در حالت فعال نمی باشد.
        /// </summary>
        public static string DocumentNotInActiveMode {
            get {
                return ResourceManager.GetString("DocumentNotInActiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در کپی کردن فایل.
        /// </summary>
        public static string ErrorInCopyFile {
            get {
                return ResourceManager.GetString("ErrorInCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حذف فایل.
        /// </summary>
        public static string ErrorInDeleteFile {
            get {
                return ResourceManager.GetString("ErrorInDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگذاری سطح دسترسی ها.
        /// </summary>
        public static string ErrorInLoadAccessLevels {
            get {
                return ResourceManager.GetString("ErrorInLoadAccessLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگذاری شهر ها.
        /// </summary>
        public static string ErrorInLoadCities {
            get {
                return ResourceManager.GetString("ErrorInLoadCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگذاری لیست استان ها.
        /// </summary>
        public static string ErrorInLoadProvinces {
            get {
                return ResourceManager.GetString("ErrorInLoadProvinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بارگذاری لیست فروشنده ها.
        /// </summary>
        public static string ErrorInLoadSellerList {
            get {
                return ResourceManager.GetString("ErrorInLoadSellerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بروزرسانی فایل.
        /// </summary>
        public static string ErrorInUpdateFile {
            get {
                return ResourceManager.GetString("ErrorInUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در آپلود فایل تصویر پروفایل.
        /// </summary>
        public static string ErrorInUpdateProfileImage {
            get {
                return ResourceManager.GetString("ErrorInUpdateProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در آپلود فایل.
        /// </summary>
        public static string ErrorInUploadFile {
            get {
                return ResourceManager.GetString("ErrorInUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در هنگام پردازش اطلاعات رخ داده است.
        /// </summary>
        public static string ErrorOccurredWhileProcessingData {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileProcessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنگام پردازش درخواست شما خطایی رخ داد. لطفا در صورت مشاهده مجدد این پیام، مورد را به بخش پشتیبانی اطلاع دهید.
        /// </summary>
        public static string ErrorOccurredWhileProcessingPleaseContactSupportDepartment {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileProcessingPleaseContactSupportDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در محاسبه مبلغ دیرکرد رخ داده است.
        /// </summary>
        public static string ErrorrInProccessDelayAmount {
            get {
                return ResourceManager.GetString("ErrorrInProccessDelayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ورود به سایت.
        /// </summary>
        public static string FailureLogin {
            get {
                return ResourceManager.GetString("FailureLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقادیر فرم را به درستی وارد کنید.
        /// </summary>
        public static string FormNotValid {
            get {
                return ResourceManager.GetString("FormNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده لیست کامل طلا و سکه کلیک کنید.
        /// </summary>
        public static string ForSeeGoldPrcieClick {
            get {
                return ResourceManager.GetString("ForSeeGoldPrcieClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده لیست کامل طلا و سکه به سامانه وارد شوید.
        /// </summary>
        public static string ForSeeGoldPrcieMustLogin {
            get {
                return ResourceManager.GetString("ForSeeGoldPrcieMustLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای انجام عملیات لغو تسویه باید وضعیت سند در حالت تسویه شده باشد.
        /// </summary>
        public static string ForUnSettleDocumentNeedDocumentStatusIsSettled {
            get {
                return ResourceManager.GetString("ForUnSettleDocumentNeedDocumentStatusIsSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای استفاده از این قابلیت به سامانه وارد شوید.
        /// </summary>
        public static string ForUseNeedToLogin {
            get {
                return ResourceManager.GetString("ForUseNeedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری پیدا نشد.
        /// </summary>
        public static string GalleryIsNotFound {
            get {
                return ResourceManager.GetString("GalleryIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری معتبر نیست.
        /// </summary>
        public static string GalleryIsNotValid {
            get {
                return ResourceManager.GetString("GalleryIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصورتی که مایل به تغییر رمز عبور کاربر نمی باشید، آن را خالی بگذارید.
        /// </summary>
        public static string IfYouNotChangePasswordLeaveEmptyInput {
            get {
                return ResourceManager.GetString("IfYouNotChangePasswordLeaveEmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز مناسب تصویر یا ویدوئو {0} در {1} پیکسل می باشد.
        /// </summary>
        public static string ImageOrVideoSizeDescription {
            get {
                return ResourceManager.GetString("ImageOrVideoSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز مناسب تصویر {0} در {1} پیکسل می باشد.
        /// </summary>
        public static string ImageSizeDescription {
            get {
                return ResourceManager.GetString("ImageSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ اقساط محاسبه شد.
        /// </summary>
        public static string InstallmentAmountIsCalculated {
            get {
                return ResourceManager.GetString("InstallmentAmountIsCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسط قابل پرداخت نمی باشد.
        /// </summary>
        public static string InstallmentIsNotPayable {
            get {
                return ResourceManager.GetString("InstallmentIsNotPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسط قابل پرداخت می باشد.
        /// </summary>
        public static string InstallmentIsPayable {
            get {
                return ResourceManager.GetString("InstallmentIsPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت تسویه این سند تا امروز ({0}) لطفا مبلغ {1} تومان واریز و رسید را از طریق &lt;a href=&quot;/Document/Payment/{1}&quot; target=&quot;_blank&quot; class=&quot;btn btn-sm btn-primary&quot;&gt;فرم ثبت پرداخت&lt;/a&gt;  ثبت نمائید.
        /// </summary>
        public static string InstantSettlementMessageForCustomer {
            get {
                return ResourceManager.GetString("InstantSettlementMessageForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فعال است.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است.
        /// </summary>
        public static string IsDuplicated {
            get {
                return ResourceManager.GetString("IsDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فعال نیست.
        /// </summary>
        public static string IsNotActive {
            get {
                return ResourceManager.GetString("IsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان فروش قسطی برای این محصول وجود ندارد.
        /// </summary>
        public static string IsNotPossibleToSellThisProductInInstallments {
            get {
                return ResourceManager.GetString("IsNotPossibleToSellThisProductInInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم مورد نظر یافت نشد.
        /// </summary>
        public static string ItemNotFount {
            get {
                return ResourceManager.GetString("ItemNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان پرداخت برای تاریخ انتخاب شده وجود ندارد (تاریخ پرداخت نمی تواند از تاریخ پرداخت های ثبت شده برای این قسط کوچکتر باشد.).
        /// </summary>
        public static string ItIsNotPossibleToPayForThisDate {
            get {
                return ResourceManager.GetString("ItIsNotPossibleToPayForThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان انجام این عملیات وجود ندارد.
        /// </summary>
        public static string ItIsNotPossibleToPerformThisOperation {
            get {
                return ResourceManager.GetString("ItIsNotPossibleToPerformThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات وام به درستی ثبت نشده است.
        /// </summary>
        public static string LoanSettingsNotRegisterd {
            get {
                return ResourceManager.GetString("LoanSettingsNotRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام با موفقیت ارسال شد.
        /// </summary>
        public static string MessageIsSuccessfulySended {
            get {
                return ResourceManager.GetString("MessageIsSuccessfulySended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد سود ماهیانه باید بین 0 تا 100 و میتواند اعشاری باشد.
        /// </summary>
        public static string MonthlyProfitPercentageDescInLoanSetting {
            get {
                return ResourceManager.GetString("MonthlyProfitPercentageDescInLoanSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد سود ماهیانه ثبت نشده است.
        /// </summary>
        public static string MonthlyProfitPercentageNotRegisterd {
            get {
                return ResourceManager.GetString("MonthlyProfitPercentageNotRegisterd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندی برای این رسید پرداخت یافت نشد.
        /// </summary>
        public static string NotFoundDocumentForThisPaymentRecipt {
            get {
                return ResourceManager.GetString("NotFoundDocumentForThisPaymentRecipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی انتخاب نشده است.
        /// </summary>
        public static string NotSelectedRecored {
            get {
                return ResourceManager.GetString("NotSelectedRecored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری انتخاب شده معتبر نمی باشد.
        /// </summary>
        public static string NotSelectedValidCustomer {
            get {
                return ResourceManager.GetString("NotSelectedValidCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری برای شما ثبت نشده است.
        /// </summary>
        public static string NotSetGalleryForYou {
            get {
                return ResourceManager.GetString("NotSetGalleryForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت شد.
        /// </summary>
        public static string OneUserIsFounded {
            get {
                return ResourceManager.GetString("OneUserIsFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف تنها برای اسناد فعال امکان پذیر است.
        /// </summary>
        public static string OnlyCanDeleteActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanDeleteActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف ضمانت سند تنها در وضعیت فعال آن سند امکان پذیر است.
        /// </summary>
        public static string OnlyCanDeleteCollateralForActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanDeleteCollateralForActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ویرایش اطلاعات، سند باید در وضعیت فعال باشد.
        /// </summary>
        public static string OnlyCanEditActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanEditActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویراش توضیحات تنها در اسناد فعال امکان پذیر است.
        /// </summary>
        public static string OnlyCanEditAdminDescriptionInActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanEditAdminDescriptionInActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ضمانت تنها در وضعیت فعال سند قابل تغییر می باشد.
        /// </summary>
        public static string OnlyCanEditCollateralDetailsForActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanEditCollateralDetailsForActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت یا ویرایش ضمانت تنها برای اسناد فعال امکان پذیر است.
        /// </summary>
        public static string OnlyCanEditOrAddCollateralForActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanEditOrAddCollateralForActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسویه فوری برای اسنادی که فعال نباشد، ممکن نیست.
        /// </summary>
        public static string OnlyCanInstantSettlementActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanInstantSettlementActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط برای اولین قسط پرداخت نشده امکان پرداخت وجود دارد.
        /// </summary>
        public static string OnlyCanPayFirstUnPayedInstallment {
            get {
                return ResourceManager.GetString("OnlyCanPayFirstUnPayedInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای پرداخت، سند باید در وضعیت فعال باشد.
        /// </summary>
        public static string OnlyCanPayForActiveDocument {
            get {
                return ResourceManager.GetString("OnlyCanPayForActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تسویه سند باید تمام اقساط آن پرداخت شده باشد.
        /// </summary>
        public static string OnlyCanSettleDocumentIfAllInstalmentsIsPayed {
            get {
                return ResourceManager.GetString("OnlyCanSettleDocumentIfAllInstalmentsIsPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت تسویه این سند، مبلغ بازگشت خورده و تخفیف را به گونه ای وارد نمائید که مانده صفر شود. در حال حاضر {0} می باشد.
        /// </summary>
        public static string OnlyCanSettleDocumentIfTotalRemainAmountIsZiro {
            get {
                return ResourceManager.GetString("OnlyCanSettleDocumentIfTotalRemainAmountIsZiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسویه سند تنها در وضعیت فعال آن سند امکان پذیر است.
        /// </summary>
        public static string OnlyCanSettleDocumentInActiveMode {
            get {
                return ResourceManager.GetString("OnlyCanSettleDocumentInActiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنها تصاویر را میتوان به عنوان شاخص انتخاب کرد.
        /// </summary>
        public static string OnlyImagesCanSetForThumbnail {
            get {
                return ResourceManager.GetString("OnlyImagesCanSetForThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه درخواستی یافت نشد.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسط قابل پرداخت یافت نشد.
        /// </summary>
        public static string PayableInstallmentNotFounded {
            get {
                return ResourceManager.GetString("PayableInstallmentNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت و ساعت واریز نمیتواند از امروز بزرگتر باشد.
        /// </summary>
        public static string PayDateTimeCanNotMoreThanDateTimeNow {
            get {
                return ResourceManager.GetString("PayDateTimeCanNotMoreThanDateTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت نمی تواند از تاریخ امروز بزرگتر باشد.
        /// </summary>
        public static string PaymentDateCanNotMorThanTodayDate {
            get {
                return ResourceManager.GetString("PaymentDateCanNotMorThanTodayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضریب جریمه باید بین 0 تا 1 و میتواند اعشاری باشد.
        /// </summary>
        public static string PenaltyFactorDescInLoanSetting {
            get {
                return ResourceManager.GetString("PenaltyFactorDescInLoanSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای روز های 30 و 31 نمی توانید سند ثبت کنید.
        /// </summary>
        public static string PersianDateCanNotBe31And30 {
            get {
                return ResourceManager.GetString("PersianDateCanNotBe31And30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کد تایید ارسال شده به تلفن همراه خود را وارد نمایید.
        /// </summary>
        public static string PleaseEnterConfirmationCodeSentToYourMobile {
            get {
                return ResourceManager.GetString("PleaseEnterConfirmationCodeSentToYourMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا رمز عبور جدید خود را وارد نمایید.
        /// </summary>
        public static string PleaseEnterYourNewPassword {
            get {
                return ResourceManager.GetString("PleaseEnterYourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا وارد سایت شوید.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط برای آخرین قسط پرداخت شده امکان لغو پرداخت وجود دارد.
        /// </summary>
        public static string PossibleCancelPaymentOnlyForLastPaidInstallment {
            get {
                return ResourceManager.GetString("PossibleCancelPaymentOnlyForLastPaidInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} به  علاقه مندی ها اضافه شد.
        /// </summary>
        public static string ProductAddedInCustomerFavorits {
            get {
                return ResourceManager.GetString("ProductAddedInCustomerFavorits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} از  علاقه مندی ها حذف شد.
        /// </summary>
        public static string ProductRemovededInCustomerFavorits {
            get {
                return ResourceManager.GetString("ProductRemovededInCustomerFavorits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید ثبت نام به شماره موبایل ارسال شد.
        /// </summary>
        public static string RegisterCustomerCodeIsSendedToMobileNumber {
            get {
                return ResourceManager.GetString("RegisterCustomerCodeIsSendedToMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من را به خاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بازیابی رمز ورود به شماره موبایل ارسال شد.
        /// </summary>
        public static string ResetPasswordCodeIsSendedToMobileNumber {
            get {
                return ResourceManager.GetString("ResetPasswordCodeIsSendedToMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجددا برای بازیابی رمز عبور تلاش کنید.
        /// </summary>
        public static string RetryResetPassword {
            get {
                return ResourceManager.GetString("RetryResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر انتخاب شده معتبر نیست.
        /// </summary>
        public static string SelectedCityIsNotValid {
            get {
                return ResourceManager.GetString("SelectedCityIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر انتخاب شده معتبر است.
        /// </summary>
        public static string SelectedCityIsValid {
            get {
                return ResourceManager.GetString("SelectedCityIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب حداقل یک مورد سطح دسترسی الزامی است.
        /// </summary>
        public static string SelectingAtLeastOneAccessLevelItemRequired {
            get {
                return ResourceManager.GetString("SelectingAtLeastOneAccessLevelItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده اجازه ثبت سند ندارد.
        /// </summary>
        public static string SellerHasNotAccessToRegisterDocument {
            get {
                return ResourceManager.GetString("SellerHasNotAccessToRegisterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فروشنده با نام {0} حذف شد.
        /// </summary>
        public static string SellerInfoByName0IsDeleted {
            get {
                return ResourceManager.GetString("SellerInfoByName0IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشنده یافت نشد.
        /// </summary>
        public static string SellerNotFound {
            get {
                return ResourceManager.GetString("SellerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود موفق به سایت.
        /// </summary>
        public static string SuccessfullyLogin {
            get {
                return ResourceManager.GetString("SuccessfullyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج موفق از سایت.
        /// </summary>
        public static string SuccessfullyLogOut {
            get {
                return ResourceManager.GetString("SuccessfullyLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسط قبلا پرداخت شده است.
        /// </summary>
        public static string TheInstallmentIsPayed {
            get {
                return ResourceManager.GetString("TheInstallmentIsPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اقساط باید بیشتر یا برابر با {0} باشد.
        /// </summary>
        public static string TheInstallmentsCountMustBeMoreThan0 {
            get {
                return ResourceManager.GetString("TheInstallmentsCountMustBeMoreThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پیام مشتری نامعتبر است.
        /// </summary>
        public static string TheMessageTypeIsInvalid {
            get {
                return ResourceManager.GetString("TheMessageTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تاییدیه منقضی شده است.
        /// </summary>
        public static string TheOtpCodeIsExpired {
            get {
                return ResourceManager.GetString("TheOtpCodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تاییدیه نامعتبر است.
        /// </summary>
        public static string TheOtpCodeIsInvalid {
            get {
                return ResourceManager.GetString("TheOtpCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تاییدیه معتبر بود.
        /// </summary>
        public static string TheOtpCodeIsVerified {
            get {
                return ResourceManager.GetString("TheOtpCodeIsVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور تغییر یافت.
        /// </summary>
        public static string ThePasswordIsChanged {
            get {
                return ResourceManager.GetString("ThePasswordIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه است.
        /// </summary>
        public static string ThePasswordIsIncorrect {
            get {
                return ResourceManager.GetString("ThePasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت مورد نظر تایید شده است.
        /// </summary>
        public static string ThePaymentReciptIsConfirmed {
            get {
                return ResourceManager.GetString("ThePaymentReciptIsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت مورد نظر تایید شده است و نمیتوان آن را حذف کرد.
        /// </summary>
        public static string ThePaymentReciptIsConfirmedAndCantRemoveIt {
            get {
                return ResourceManager.GetString("ThePaymentReciptIsConfirmedAndCantRemoveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید پرداخت مورد نظر در وضعیت تایید نشده است.
        /// </summary>
        public static string ThePaymentReciptIsRejected {
            get {
                return ResourceManager.GetString("ThePaymentReciptIsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول {0} مشاهده شد.
        /// </summary>
        public static string TheProductIsVisited {
            get {
                return ResourceManager.GetString("TheProductIsVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر نامعتبر است.
        /// </summary>
        public static string TheUserIsInvalid {
            get {
                return ResourceManager.GetString("TheUserIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string TheUsernameAndPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("TheUsernameAndPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا تلفن همراه اشتباه است.
        /// </summary>
        public static string TheUsernameOrMobileIsIncorrect {
            get {
                return ResourceManager.GetString("TheUsernameOrMobileIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تاییدیه ارسال شد.
        /// </summary>
        public static string TheVerifyCodeISended {
            get {
                return ResourceManager.GetString("TheVerifyCodeISended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مشتری، هیچ شماره ضروری ندارد.
        /// </summary>
        public static string ThisCustomerHaventAEssentialNumber {
            get {
                return ResourceManager.GetString("ThisCustomerHaventAEssentialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این سند ضمانتی ثبت نشده است.
        /// </summary>
        public static string ThisDocumentHaventACollateral {
            get {
                return ResourceManager.GetString("ThisDocumentHaventACollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا برای ورود، بعد از {0} دقیقه مجددا تلاش کنید.
        /// </summary>
        public static string TryToLoginAfterXMin {
            get {
                return ResourceManager.GetString("TryToLoginAfterXMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند پرداخت نشده وجود ندارد.
        /// </summary>
        public static string UpPaymentInstallmentNotFound {
            get {
                return ResourceManager.GetString("UpPaymentInstallmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربر فعال است.
        /// </summary>
        public static string UserIsActive {
            get {
                return ResourceManager.GetString("UserIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربر غیرفعال است.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما مسدود است.
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کاربر، مشتری نیست.
        /// </summary>
        public static string UserNotACustomer {
            get {
                return ResourceManager.GetString("UserNotACustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با نام کاربری {0} یافت نشد.
        /// </summary>
        public static string UserNotFoundByUsername {
            get {
                return ResourceManager.GetString("UserNotFoundByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور کاربر بازنشانی شد.
        /// </summary>
        public static string UserPasswordIsReseted {
            get {
                return ResourceManager.GetString("UserPasswordIsReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور {0} بازنشانی شد.
        /// </summary>
        public static string UserPasswordIsReseted0 {
            get {
                return ResourceManager.GetString("UserPasswordIsReseted0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز مناسب ویدوئو {0} در {1} پیکسل می باشد.
        /// </summary>
        public static string VideoSizeDescription {
            get {
                return ResourceManager.GetString("VideoSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید.
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما پیام شما را به درستی دریافت کردیم.
        /// </summary>
        public static string WeRecivedYouMessage {
            get {
                return ResourceManager.GetString("WeRecivedYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ثبت محصول را دارید.
        /// </summary>
        public static string YouAreAllowedToRegisterProduct {
            get {
                return ResourceManager.GetString("YouAreAllowedToRegisterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به ویرایش این اطلاعات نمی باشید.
        /// </summary>
        public static string YouAreNotAllowedToEditThisInformation {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToEditThisInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه ثبت محصول را ندارید.
        /// </summary>
        public static string YouAreNotAllowedToRegisterProduct {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToRegisterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی به این بخش ندارید، با مدیریت تماس بگیرید.
        /// </summary>
        public static string YouDontHaveAccessContactAdministrator {
            get {
                return ResourceManager.GetString("YouDontHaveAccessContactAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما مسدود است.
        /// </summary>
        public static string YourAccountIsBlocked {
            get {
                return ResourceManager.GetString("YourAccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ویرایش اطلاعات با موفقیت ارسال شد.
        /// </summary>
        public static string YourEditInformationRequestSuccessfulySended {
            get {
                return ResourceManager.GetString("YourEditInformationRequestSuccessfulySended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما با موفقیت ثبت شد.
        /// </summary>
        public static string YourMessageIsRegistered {
            get {
                return ResourceManager.GetString("YourMessageIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور شما با موفقیت تغییر یافت.
        /// </summary>
        public static string YourPasswordChangedSuccessfuly {
            get {
                return ResourceManager.GetString("YourPasswordChangedSuccessfuly", resourceCulture);
            }
        }
    }
}
