//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gold.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gold.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی نمیتواند بیشتر از 16 رقم باشد.
        /// </summary>
        public static string BankCardNumberMaxLength {
            get {
                return ResourceManager.GetString("BankCardNumberMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی نمیتواند کمتر از 16 رقم باشد.
        /// </summary>
        public static string BankCardNumberMinLength {
            get {
                return ResourceManager.GetString("BankCardNumberMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با {1} یکسان نیست..
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد.
        /// </summary>
        public static string FileChecker {
            get {
                return ResourceManager.GetString("FileChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت {0} معتبر نمی باشد.
        /// </summary>
        public static string FileExtentionChecker {
            get {
                return ResourceManager.GetString("FileExtentionChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل آپلود شده بیش از حد مجاز است.
        /// </summary>
        public static string FileSizeChecker {
            get {
                return ResourceManager.GetString("FileSizeChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت {0} معتبر نمی باشد.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} نباید بیشتر از {1} باشد.
        /// </summary>
        public static string MaximumLength {
            get {
                return ResourceManager.GetString("MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند بیشتر از {1} کاراکتر باشد.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند بیشتر از {1} رقم باشد.
        /// </summary>
        public static string MaxLengthNumber {
            get {
                return ResourceManager.GetString("MaxLengthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند کمتر از {1} کاراکتر باشد.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت {0} معتبر نمی باشد.
        /// </summary>
        public static string MonyFormat {
            get {
                return ResourceManager.GetString("MonyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بیشتر از {1} باشد.
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  و {1} با هم مطابقت ندارد.
        /// </summary>
        public static string NotMatch {
            get {
                return ResourceManager.GetString("NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمیتواند بزرگتر از {1} باشد.
        /// </summary>
        public static string NotMoreThan {
            get {
                return ResourceManager.GetString("NotMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت {0} باید عدد باشد.
        /// </summary>
        public static string Numberic {
            get {
                return ResourceManager.GetString("Numberic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} فقط میتواند عدد و حروف باشد.
        /// </summary>
        public static string OnlyAlphanumeric {
            get {
                return ResourceManager.GetString("OnlyAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط مجاز به استفاده از کاراکترهای فارسی می باشید.
        /// </summary>
        public static string OnlyInputPersianChars {
            get {
                return ResourceManager.GetString("OnlyInputPersianChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت ورودی باید عدد باشد.
        /// </summary>
        public static string OnlyNumberInput {
            get {
                return ResourceManager.GetString("OnlyNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد.
        /// </summary>
        public static string PersianMobileNumber {
            get {
                return ResourceManager.GetString("PersianMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد.
        /// </summary>
        public static string PersianNationalCode {
            get {
                return ResourceManager.GetString("PersianNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  باید بین {1} تا {2} باشد.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} اجباری است.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  باید بین {1} تا {2} باشد.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} معتبر نمی باشد. زمان باید بین 00:00 تا 23:59 وارد شود.
        /// </summary>
        public static string TimeChecker {
            get {
                return ResourceManager.GetString("TimeChecker", resourceCulture);
            }
        }
    }
}
